---
driver:
  name: ec2
  aws_ssh_key_id: <redacted>
  region: <redacted>
  availability_zone: <redacted>
  subnet_id: <redacted>
  instance_type: t2.large
  # Windows Server 2016 Base image from AWS Marketplace
  image_id: ami-f0df538f
  security_group_ids: ["<redacted>"]
  tags:
  retryable_tries: 300

provisioner:
  name: chef_zero

transport:
  ssh_key: <redacted>
  username: Administrator
  elevated: true

verifier:
  name: inspec

platforms:
  - name: windows-2016
    transport:
      name: winrm
    driver:
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            delete_on_termination: true

suites:
  - name: default
    run_list:
      - recipe[cps_certificate::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
